M48
; DRILL file {KiCad 7.0.11+1} date Tue 07 May 2024 09:39:46 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-07T09:39:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X3.1496Y-2.0571
X3.1496Y-2.2343
T2
X3.937Y-5.0276
M30
